name: PlayerShop
main: me.joff1507.pshop.PlayerShop
version: 1.0
api-version: 1.20

commands:
  pshop:
    description: Shop admin commands
    usage: /<command>
    permission: pshop.admin

permissions:
  pshop.admin:
    description: Accès complet aux commandes administratives
    default: op
  pshop.sell:
    description: Permet de vendre via un coffre
    default: true
  pshop.buy:
    description: Permet d'acheter dans un shop
    default: true